apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
   replicas: 2
   selector:
      matchLabels:
         app: my-hello
   template:
      metadata:
         labels:
           app: my-hello
      spec:
         containers:
           - name: my-deployment
             image: suman4197/custom-image:1.0
             ports:
               - containerPort: 80
--------------------------------------
apiVersion: v1
kind: Service
metadata:
   name: service-nodeport
spec:
   type: NodePort
   selector:
      matchLabels:
        app: my-hello
   ports:
      - name: http
        nodePort: 30080
        port: 30081
        targetPort: 80
